"""Ria SWIFT Confirmation parser.

Parses .eml SWIFT MX (PACS.008) confirmation emails from Ria into canonical
settlement events.

Source: Ria sends emails to transmissions@riaenvia.net with subject
"52447 Cadorim S.A | SWIFT Confirmation". The body contains an HTML-escaped
PACS.008 XML message detailing the EUR settlement routed via Bank of America
London (BOFAGB22) to Cadorim's BMI account (MR1300024000011000003547223).

Key fields extracted from the PACS.008 XML:
- IntrBkSttlmDt       → settlement date (value date)
- IntrBkSttlmAmt @Ccy → amount + currency (always EUR)
- UETR                → globally unique end-to-end reference (idempotency key)
- MsgId / EndToEndId  → Ria internal reference (matches Ria CorrespPayment file)
- BICFI (sender)      → RIAIUS66XXX

Idempotency: UETR is a UUID generated by Ria; reusing a UETR is a network
violation. We use it as the settlement event id, so re-running the parser
over the same mail folder produces zero new events.
"""
from __future__ import annotations

import email
import glob
import html
import os
import re
from dataclasses import dataclass, asdict
from email import policy
from typing import Iterable

CADORIM_BMI_IBAN = "MR1300024000011000003547223"
RIA_SENDER_BIC = "RIAIUS66XXX"


@dataclass
class RiaSwiftSettlement:
    """Canonical Ria settlement event, schema-compatible with ingest.py output."""

    id: str                  # S-ria-{UETR-short}
    partner_code: str        # "ria"
    Par_l: str               # "ria"
    Bank_t: str              # "bmi"
    date: str                # YYYY-MM-DD (IntrBkSttlmDt)
    date_s: str              # alias for engine
    amount_foreign: float    # EUR
    Amount_s: float          # alias
    currency: str            # "EUR"
    Cur_k: str               # alias
    fx_rate_settlement: float
    fx_settlement_rate: float
    fx_reference_rate: float
    amount_mru: float
    reference: str           # MsgId / EndToEndId / InstrId
    uetr: str                # SWIFT UUID (idempotency key)
    sender_bic: str
    beneficiary_iban: str
    source: str              # "ria_swift_email"
    source_file: str         # filename (basename)

    def to_dict(self) -> dict:
        return asdict(self)


def _extract_xml_text(eml_path: str) -> str | None:
    """Read .eml, strip HTML tags, decode entities, return XML-shaped text."""
    with open(eml_path, "rb") as f:
        msg = email.message_from_binary_file(f, policy=policy.default)
    body = msg.get_body(preferencelist=("plain", "html"))
    if body is None:
        return None
    content = body.get_content()
    text = re.sub(r"<[^>]+>", " ", content)        # 1) strip outer HTML
    text = html.unescape(text).replace("\xa0", " ")  # 2) decode entities
    return re.sub(r"\s+", " ", text)                  # 3) collapse whitespace


def _find(tag: str, where: str) -> str | None:
    m = re.search(rf"<\s*{tag}[^>]*>\s*([^<]+?)\s*<\s*/\s*{tag}", where)
    return m.group(1).strip() if m else None


def parse_one(eml_path: str, fx_eur: float = 42.5) -> RiaSwiftSettlement | None:
    """Parse a single SWIFT Confirmation email. Returns None if not a valid SWIFT."""
    text = _extract_xml_text(eml_path)
    if not text:
        return None

    # Required: settlement date + amount + UETR
    date = _find("IntrBkSttlmDt", text)
    amt_match = re.search(
        r'IntrBkSttlmAmt[^>]*Ccy="([A-Z]+)"[^>]*>\s*([0-9.,]+)', text
    )
    uetr = _find("UETR", text)

    if not (date and amt_match and uetr):
        return None  # not a SWIFT confirmation (could be Wire, marketing, etc.)

    ccy = amt_match.group(1)
    amount = float(amt_match.group(2))
    reference = _find("MsgId", text) or _find("EndToEndId", text) or _find("InstrId", text) or ""
    sender_bic = _find("BICFI", text) or ""
    # Beneficiary IBAN — find Mauritanian IBAN among all IBANs in payload
    ibans = re.findall(r"\b(MR\d{2}\d{20,30})\b", text)
    beneficiary_iban = ibans[0] if ibans else ""

    short_uetr = uetr[:13]
    amount_mru = round(amount * fx_eur, 2)

    return RiaSwiftSettlement(
        id=f"S-ria-{short_uetr}",
        partner_code="ria",
        Par_l="ria",
        Bank_t="bmi",
        date=date,
        date_s=date,
        amount_foreign=amount,
        Amount_s=amount,
        currency=ccy,
        Cur_k=ccy,
        fx_rate_settlement=fx_eur,
        fx_settlement_rate=fx_eur,
        fx_reference_rate=fx_eur,
        amount_mru=amount_mru,
        reference=reference,
        uetr=uetr,
        sender_bic=sender_bic,
        beneficiary_iban=beneficiary_iban,
        source="ria_swift_email",
        source_file=os.path.basename(eml_path),
    )


def parse_directory(
    mails_dir: str,
    from_date: str = "2025-01-01",
    to_date: str = "2026-04-01",
    fx_eur: float = 42.5,
) -> list[RiaSwiftSettlement]:
    """Parse all Ria SWIFT confirmation .eml files in a directory.

    Idempotent: caller deduplicates by `id` (=UETR-short) when merging into
    the engine's settlement list.
    """
    pattern = os.path.join(mails_dir, "*SWIFT_Confirmation*.eml")
    files = sorted(glob.glob(pattern))
    settlements: list[RiaSwiftSettlement] = []
    skipped = 0
    out_of_range = 0
    for fp in files:
        try:
            s = parse_one(fp, fx_eur=fx_eur)
        except Exception:
            skipped += 1
            continue
        if s is None:
            skipped += 1
            continue
        if not (from_date <= s.date < to_date):
            out_of_range += 1
            continue
        settlements.append(s)

    settlements.sort(key=lambda x: x.date)
    return settlements


def parse_all_mail_folders(
    settlements_dir: str,
    from_date: str = "2025-01-01",
    to_date: str = "2026-04-01",
    fx_eur: float = 42.5,
) -> list[RiaSwiftSettlement]:
    """Scan every subfolder of settlements_dir for Ria SWIFT emails.

    Handles the dual `mails/` + `mails (1)/` layout. Deduplicates by UETR.
    """
    seen: dict[str, RiaSwiftSettlement] = {}
    for sub in sorted(os.listdir(settlements_dir)):
        full = os.path.join(settlements_dir, sub)
        if not os.path.isdir(full):
            continue
        for s in parse_directory(full, from_date, to_date, fx_eur=fx_eur):
            # First occurrence wins; identical UETR ⇒ same event
            seen.setdefault(s.uetr, s)
    return sorted(seen.values(), key=lambda x: x.date)


if __name__ == "__main__":
    # Quick smoke test when run directly
    here = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
    setts = parse_all_mail_folders(os.path.join(here, "data", "settlements"))
    print(f"Parsed {len(setts)} unique Ria SWIFT settlements")
    if setts:
        total_eur = sum(s.amount_foreign for s in setts)
        print(f"  Date range: {setts[0].date} → {setts[-1].date}")
        print(f"  Total EUR : {total_eur:,.2f}")
        print(f"  Total MRU : {sum(s.amount_mru for s in setts):,.2f}")
